apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: ai-core-pipeline
data:
  S3_ENDPOINT: http://minio.ai-core-pipeline.svc.cluster.local:9000
  S3_BUCKET: lake
  AWS_DEFAULT_REGION: us-east-1
