apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  namespace: ai-core-pipeline
type: Opaque
stringData:
  # Postgres
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow

  # MinIO (S3 compatible)
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123
