# Apache Airflow official Helm chart values (minimal, K8sExecutor)
executor: "KubernetesExecutor"

images:
  airflow:
    repository: local/airflow-custom
    tag: dev
    pullPolicy: IfNotPresent
  migrationsWaitTimeout: 300

postgresql:
  enabled: false

data:
  metadataSecretName: airflow-metadata-secret

webserver:
  service:
    type: ClusterIP

scheduler:
  replicas: 1

triggerer:
  enabled: true

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/will-d-wang/ai-core-capstone.git"
    branch: "main"
    subPath: "dags"
    wait: 30
    depth: 1

createUserJob:
  useHelmHooks: true

migrateDatabaseJob:
  enabled: true
  useHelmHooks: false
